@startuml
start
:Работодатель открывает отклик;
:Выбирает действие;
if (Назначить интервью?) then (Да)
  :Выбрать дату и время;
  :Создать событие в календаре;
  :Статус «Интервью назначено»;
else (Нет)
  :Изменить статус вручную;
endif
:Отправить уведомление студенту;
stop
@enduml
