@startuml
start
:Получить профиль студента;
:Получить активные вакансии;
:Извлечь признаки;
:Посчитать score вакансий;
:Отфильтровать нерелевантные;
:Отсортировать топ-N;
:Сформировать объяснения;
stop
@enduml
